add more questions and answers to pun
AlexLakatos/computer-puns pull request #53
Opened 2020-10-03 18:30 UTC by muaz234

add questions and the answers from line 269 to 296 as counted from my text editor. just for fun questions and answers

2020-10-03 20:04 UTC, AlexLakatos commented on puns.json
> +=======
This is not valid JSON. Could you please fix it?

2020-10-03 20:04 UTC, AlexLakatos commented on puns.json
> +    "punchline": "A: Foo Bar"
This looks like it's a duplicate pun.

2020-10-03 20:06 UTC, AlexLakatos commented on puns.json
> +    "punchline": "A: They both become useless when you open Windows"
This pun already exists further up, in line 67.

2020-10-03 20:06 UTC, AlexLakatos commented on puns.json
> +  },
I didn't think these were particularly funny, could you remove them from the PR please?

2020-10-03 20:07 UTC, AlexLakatos requested changes
Thanks for the PR, I've got a few changes I wanted before I accept it.

2020-10-04 01:43 UTC, muaz234 commented
Hi Alex, i have made the necessary changes. Appreciate if you could review and merge them if everything is correct. 

Thanks

2020-10-04 19:44 UTC, AlexLakatos approved these changes
Thanks for making the changes! LGTM 💈

2020-10-04 19:44 UTC, merged